version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 7845:7845

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    depends_on:
      - server